<?php
// Template Name: Hf4M Hair Loss
get_header(); ?>
	<div class="page-aboutus full-width">
		<h1><?php the_title();?></h1>
		<hr />
		<p>According to the American Hair Loss Association, “Androgenetic alopecia or common male pattern baldness (MPB) accounts for more than 95% of hair loss in men. By the age of thirty-five two-thirds of American men will experience some degree of appreciable hair loss and by the age of 50 approximately 85% of men have significantly thinning hair. Approximately twenty five percent of men who suffer with male pattern baldness begin the painful process before they reach the age of twenty-one”.</p>
		<p>As the CEO/Founder of Hair Fusion 4 Men, The level of hypocrisy surrounding hair loss sufferers in search of a solution within our society continues to amaze me. It’s hard to believe that in 2015 men seeking a hair loss solution is not expected versus still being a taboo conversation taking place behind closed doors with a potential hair loss provider.</p>
		<p>As a hair loss sufferer myself one has to wonder why that is? I have come up with several possibilities that may provide insight.</p>
		<p>Throughout the course of my lifetime as well as others, hair loss has always been associated with getting old, being unattractive or undesirable, less than etc. We learned at an early age going through adolescence into young adulthood the impact that hair or a lack there of can have on our self-perception and the way that we are perceived by others. </p>
		<p>I can remember being in elementary school and seeing a bald student that had cancer for the first time. All students could talk about is “what is wrong with him? He has a bald head”, totally lacking the empathy that a situation of this magnitude should be dealt with. While we all know how cruel young kids and teenagers can be to one another, one would assume as adults a level of empathy would be applied as it pertains to someone in search of a hair loss solution to better themselves.</p>
		<p>Yet and still, as a man of color it almost feels as though when we start losing our hair the number one solution considered by unanimous decision is to shave our head bald or accept our demise with grace. We don’t know what the response will be should we expose our attempt at a hair loss solution. Not to mention if the solution is unsuccessful, our pain is doubled and you can no longer claim that it’s not a big deal and you don’t really care.</p>
		<p>While I have repeatedly stated that there is nothing wrong with a bald head or a receding hairline, that look was not for me, which led me to create Hair Fusion 4 Men.</p>
		<p>In my humble opinion hair loss is a terrible disease and we as hair loss sufferers are in search of a cure. Is doing something about your hair loss so different from the woman that puts a weave on her head, a person getting liposuction, Breast implants or veneers? We support people in search of a solution in these areas, so why would we not be in support of a solution for a problem that dates back to the days of Caesar and beyond? </p>
		<p>I believe that we as hair loss sufferers are a big part of the problem. How many times have you heard a hair loss sufferer self-deprecate as it pertains to his hair loss almost in what seems to be an attempt to put himself down before anyone else can?</p>
		<p>As I hold myself to the same level of accountability that I am talking to you about, I created Hair Fusion 4 men in 2006. It was perfected by 2007 and yet I never once considered taking it to market until 2010 and here we are just now putting it out in 2015! I have a very good understanding of the insecurities and mindset of a hair loss sufferer and what they have to deal with psychologically because I have lived it.  </p>
		<p>For me it was all about concealing my hair loss. I didn’t want anybody to know that I was losing my hair! And so I had never considered tuning this product into a business. The shame associated with hair loss in my mind never allowed me to visualize the obvious opportunity to make millions by providing a hair loss solution to the obvious underserved market of men of color.</p>
		<p>This example speaks to the depth of embarrassment, pain and suffering that so many of us carry once we lose our hair. After years of successfully wearing Hair Fusion 4 Men, all the continual compliments about my hair, all the while not knowing that I was actually bald, I began to realize it makes no sense that there are so many of us walking around carrying this pain and embarrassment when I have a non-invasive solution created specifically for men of color.</p>
		<p>Bottom line, as hair loss sufferers we must band together in support and be non-apologetic in our search for a viable hair loss solution, but before we can change the minds of others and how they view hair loss we must first start to deal with our own pain and insecurities in accepting our situation while understanding that we can look and feel the way we used too. </p>
		<p>There is no victory without a struggle, and the battle will start one hair loss sufferer at time refusing to be made to feel less than for trying to better themselves, their situation, and well-being…</p>
		<p>My name is Ryan Knight and I am Bald!</p>

	</div>
<?php get_footer(); ?>